### ISSUE TITLE
Set-up readthedocs.io docs

### ISSUE THREAD

**Issue by aasseman** [semiotic-ai/autoagora#3]

**Comment by tkornuta-semiotic** [comment]
Free version of RTD for open-source: https://readthedocs.org/

**Comment by tkornuta-semiotic** [comment]
@aasseman we will have to setup semiotic organization (and add users  on https://readthedocs.org/) - adding that as a separate task

**Comment by aasseman** [comment]
Abandoned in favor of mkdocs + gh-pages, as in https://github.com/semiotic-ai/autoagora-agents/pull/33
